apiVersion: apps/v1
kind: Deployment
metadata:
  name: logukyugj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logukyugj
  template:
    metadata:
      labels:
        app: logukyugj
    spec:
      containers:
      - image: okteto.dev/logukyugj:latest
        name: logukyugj
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d6222cf6-a618-4112-8528-85e11f066e8e"
        - name: Vless_Path
          value: "/k67ik7uj6"
        - name: Vmess_UUID
          value: "d6222cf6-a618-4112-8528-85e11f066e8e"
        - name: Vmess_Path
          value: "/tyjrt6y45"
        - name: Share_Path
          value: "/v2link"
